# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Entertainment Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  entertainment:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Entertainment Metric - YouTube, Chess, AniList
      - name: Entertainment Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: entertainment.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: anxlz
          template: classic
          base: ""
          config_octicon: yes
          config_timezone: Africa/Cairo
          config_twemoji: yes
          
          plugin_anilist: yes
          plugin_anilist_limit: 10
          plugin_anilist_limit_characters: 22
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites
          plugin_anilist_shuffle: yes
          plugin_anilist_user: anxlz
          
          plugin_chess: yes
          plugin_chess_user: .user.login
          plugin_chess_token: ${{ secrets.CHESS_TOKEN }}
          plugin_chess_animation: '{"size": 40, "delay": 3, "duration": 0.6}'
          plugin_chess_platform: lichess.org
          
          plugin_music: yes
          plugin_music_provider: youtube
          plugin_music_token: ${{ secrets.YOUTUBE_COOKIE }}
          plugin_music_limit: 4
          plugin_music_mode: recent
          plugin_music_played_at: yes
          plugin_music_user: anxz
