# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Main Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Main Metric
      - name: Main Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: main.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: anxlz
          template: classic
          base: header, activity, community, repositories, metadata
          base_hireable: yes
          base_indepth: yes
          config_octicon: yes
          config_timezone: Africa/Cairo
          config_twemoji: yes
          config_order: base.header, isocalendar, languages, notable, discussions, topics
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          
          plugin_16personalities: yes
          plugin_16personalities_url: "https://www.16personalities.com/infj-personality"
          plugin_16personalities_sections: personality, traits
          plugin_16personalities_scores: yes
          
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
          plugin_achievements_only: polyglot, stargazer, sponsor, deployer, member, maintainer, developer, scripter, packager, explorer, infographile, manager
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 6
          
          plugin_calendar: yes
          plugin_calendar_limit: 1
          
          plugin_code: yes
          plugin_code_days: 3
          plugin_code_lines: 12
          plugin_code_load: 400
          plugin_code_visibility: public
          
          plugin_contributors: yes
          plugin_contributors_base: ""
          plugin_contributors_head: master
          plugin_contributors_ignored: bot
          plugin_contributors_contributions: yes
          plugin_contributors_sections: contributors, categories
          plugin_contributors_categories: |
            {
              "ðŸ“š Documentation": ["README.md", "docs/**"],
              "ðŸ’» Code": ["source/**"],
              "#ï¸âƒ£ Others": ["*"]
            }
          
          plugin_discussions: yes
          plugin_discussions_categories: yes
          
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_indepth: yes
          plugin_followup_sections: repositories
          
          plugin_fortune: yes
          plugin_gists: yes
          
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_trim: yes
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          
          plugin_introduction: yes
          plugin_introduction_title: yes
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 2
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_indepth: yes
          
          plugin_leetcode: yes
          plugin_leetcode_limit_recent: 2
          plugin_leetcode_limit_skills: 10
          plugin_leetcode_sections: solved
          plugin_leetcode_user: anxlz
          
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_repositories: yes
          plugin_notable_self: yes
          plugin_notable_types: commit
          
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following

          plugin_posts: yes
          plugin_posts_source: dev.to
          plugin_posts_user: anxlz
          plugin_posts_descriptions: yes
          plugin_posts_covers: yes
          plugin_posts_limit: 4
          
          plugin_projects: yes
          plugin_projects_limit: 4
          plugin_projects_descriptions: yes
          
          plugin_reactions: yes
          plugin_reactions_display: absolute
          plugin_reactions_limit: 200
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_limit_issues: 100
          
          plugin_repositories: yes
          plugin_repositories_order: featured, pinned, starred, random, contributors, stargazers, watchers, sponsors
          plugin_repositories_featured: anxlz/QuizApp
          
          plugin_rss: yes
          plugin_rss_source: https://news.ycombinator.com/rss
          plugin_rss_limit: 4
          
          plugin_screenshot: yes
          plugin_screenshot_background: yes
          plugin_screenshot_mode: image
          plugin_screenshot_selector: body
          plugin_screenshot_title: Recent Project
          plugin_screenshot_url: https://adasablog.vercel.app/
          plugin_screenshot_viewport: '{"width": 1280, "height": 1280}'
          
          plugin_skyline: yes
          plugin_skyline_year: 2025
          plugin_skyline_frames: 6
          plugin_skyline_quality: 1
          plugin_skyline_compatibility: yes
          plugin_skyline_settings: '{"url": "https://honzaap.github.io/GithubCity?name=${login}&year=${year}", "ready": "[...document.querySelectorAll(''.display-info span'')].map(span => span.innerText).includes(''${login}'')", "wait": 4, "hide": ".github-corner, .footer-link, .buttons-options, .mobile-rotate, .display-info span:first-child"}'
          
          plugin_sponsors: yes
          plugin_sponsors_sections: goal, list, about
          plugin_sponsors_size: 24
          plugin_sponsors_title: Sponsor Me!
          
          plugin_sponsorships: yes
          plugin_sponsorships_sections: amount, sponsorships
          plugin_sponsorships_size: 24
          
          plugin_stackoverflow: yes
          plugin_stackoverflow_limit: 2
          plugin_stackoverflow_lines: 4
          plugin_stackoverflow_lines_snippet: 2
          plugin_stackoverflow_sections: answers-top, questions-recent
          plugin_stackoverflow_user: 25005539
          
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_charts_type: graph
          plugin_stargazers_days: 14
          
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit: 2
          plugin_starlists_limit_languages: 8
          plugin_starlists_limit_repositories: 2
          plugin_starlists_shuffle_repositories: yes
          
          plugin_stars: yes
          plugin_stars_limit: 4
          
          plugin_stock: yes
          plugin_stock_token: ${{ secrets.STOCK_TOKEN }}
          plugin_stock_duration: 1d
          plugin_stock_interval: 5m
          plugin_stock_symbol: TSLA
          
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          
          plugin_traffic: yes
          
          repositories_forks: yes
