# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Terminal Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  terminal:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Terminal Metric
      - name: Terminal Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: terminal.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: anxlz
          template: terminal
          base: header, activity, community, repositories, metadata
          base_hireable: yes
          base_indepth: yes
          base_skip: yes
          config_octicon: yes
          config_timezone: Africa/Cairo
          config_twemoji: yes
          repositories_forks: yes
